version: "3.7"

services:

  sql:
    restart: unless-stopped
    build: ./sql
    image: wisdman/oitp-isov-sql
    volumes:
      - data-volume:/var/lib/postgresql/data
    env_file:
      - ./.environment
    networks:
      default:

  api-patterns:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_NAME=patterns
    image: wisdman/oitp-isov-api-patterns
    env_file:
      - ./.environment
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  # api-auth:
  #   restart: unless-stopped
  #   build:
  #     context: ./api
  #     dockerfile: auth.Dockerfile
  #   image: wisdman/oitp-isov-api-auth
  #   env_file:
  #     - ./.environment
  #   networks:
  #     default:

  app:
    restart: unless-stopped
    build: ./frontends/app
    image: wisdman/oitp-isov-frontend-app
    networks:
      default:

  nginx:
    restart: unless-stopped
    build: ./nginx
    image: wisdman/oitp-isov-nginx
    depends_on:
      - api-patterns
      - app
    links:
      - api-patterns
      - app
    networks:
      default:

volumes:
  data-volume:
