version: "3.7"

services:

  sql:
    restart: unless-stopped
    build: ./sql
    image: oitp-isov/sql
    volumes:
      - data-volume:/var/lib/postgresql/data
    secrets:
      - secret-sql
    environment:
      - POSTGRES_DB=oitp
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD_FILE=/run/secrets/secret-sql
    networks:
      default:

  api-auth:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_NAME=auth
    image: oitp-isov/api-auth
    secrets:
      - secret-api
    environment:
      - PGAPPNAME=auth
      - PGHOST=sql
      - PGSSLMODE=disable
      - PGDATABASE=oitp
      - PGUSER=api
      - PGPASSWORD=API-P@Ssw0rd
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  api-recommendation:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_NAME=recommendation
    image: oitp-isov/api-recommendation
    secrets:
      - secret-api
    environment:
      - PGAPPNAME=recommendation
      - PGHOST=sql
      - PGSSLMODE=disable
      - PGDATABASE=oitp
      - PGUSER=api
      - PGPASSWORD=API-P@Ssw0rd
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  api-user:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_NAME=user
    image: oitp-isov/api-user
    secrets:
      - secret-api
    environment:
      - PGAPPNAME=user
      - PGHOST=sql
      - PGSSLMODE=disable
      - PGDATABASE=oitp
      - PGUSER=api
      - PGPASSWORD=API-P@Ssw0rd
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  api-training:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_NAME=training
    image: oitp-isov/api-training
    secrets:
      - secret-api
    environment:
      - PGAPPNAME=training
      - PGHOST=sql
      - PGSSLMODE=disable
      - PGDATABASE=oitp
      - PGUSER=api
      - PGPASSWORD=API-P@Ssw0rd
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  app:
    restart: unless-stopped
    build: ./frontends/app
    image: oitp-isov/frontend-app
    networks:
      default:

  nginx:
    restart: unless-stopped
    build: ./nginx
    image: oitp-isov/nginx
    depends_on:
      - api-auth
      - api-training
      - app
    links:
      - api-auth
      - api-training
      - app
    networks:
      default:

volumes:
  data-volume:

secrets:
  secret-sql:
    file: ./secret-sql.env
  secret-api:
    file: ./secret-api.env
