version: "3.7"

services:

  sql:
    restart: unless-stopped
    build: ./sql
    image: oitp-isov/sql
    volumes:
      - data-volume:/var/lib/postgresql/data
    secrets:
      - secret-sql
    environment:
      - POSTGRES_DB=oitp
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD_FILE=/run/secrets/secret-sql
    networks:
      default:

  api-auth:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_NAME=auth
    image: oitp-isov/auth
    secrets:
      - secret-api
    environment:
      - PGHOST=sql
      - PGSSLMODE=disable
      - PGDATABASE=oitp
      - PGUSER=api
    networks:
      default:

  # api-patterns:
  #   restart: unless-stopped
  #   build:
  #     context: ./api
  #     args:
  #       - APP_NAME=patterns
  #   image: oitp-isov/patterns
  #   env_file:
  #     - ./.environment
  #   depends_on:
  #     - sql
  #   links:
  #     - sql
  #   networks:
  #     default:

  # api-auth:
  #   restart: unless-stopped
  #   build:
  #     context: ./api
  #     dockerfile: auth.Dockerfile
  #   image: wisdman/oitp-isov-api-auth
  #   env_file:
  #     - ./.environment
  #   networks:
  #     default:

  app:
    restart: unless-stopped
    build: ./frontends/app
    image: oitp-isov/frontend-app
    networks:
      default:

  nginx:
    restart: unless-stopped
    build: ./nginx
    image: oitp-isov/nginx
    depends_on:
      - api-auth
      - app
    links:
      - api-auth
      - app
    networks:
      default:

volumes:
  data-volume:

secrets:
  secret-sql:
    file: ./secret-sql.env
  secret-api:
    file: ./secret-api.env