version: "3.7"

services:

  sql:
    restart: unless-stopped
    build: ./sql
    image: oitp-isov/sql
    volumes:
      - data-volume:/var/lib/postgresql/data
    environment:
      - LANG=ru_RU.utf8
      - PGDATABASE=oitp
    secrets:
      - api-admin
      - api-payment
      - api-public
      - api-self
      - daemon-cron
      - daemon-msg
      - daemon-payment
    networks:
      default:

  daemon-sql-cron:
    restart: unless-stopped
    build:
      context: ./backends
      args:
        - APP_PATH=daemons/sql-cron
    image: oitp-isov/daemon-sql-cron
    secrets:
      - daemon-cron
    environment:
      - PGAPPNAME=daemon-sql-cron
      - PGHOST=sql
      - PGDATABASE=oitp
      - PGUSER=daemon-cron
      - PGPASSWORD_FILE=/run/secrets/daemon-cron
      - PGPOOL_SIZE=3
      - PGLOG_LEVEL=WARN
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  daemon-msg-email:
    restart: unless-stopped
    build:
      context: ./backends
      args:
        - APP_PATH=daemons/msg-email
    image: oitp-isov/daemon-msg-email
    secrets:
      - daemon-msg
    environment:
      - PGAPPNAME=daemon-msg-email
      - PGHOST=sql
      - PGDATABASE=oitp
      - PGUSER=daemon-msg
      - PGPASSWORD_FILE=/run/secrets/daemon-msg
      - PGPOOL_SIZE=3
      - PGLOG_LEVEL=WARN
      - SMTP_SERVER=smtp.elasticemail.com
      - SMTP_PORT=2525
      - SMTP_USER=wisdman@wisdman.io
      - SMTP_NAME=VLLSchool
      - SMTP_FROM=noreply@vllschool.com
      - SMTP_TPL_DIR=/templates
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  api-auth:
    restart: unless-stopped
    build:
      context: ./backends
      args:
        - APP_PATH=api/auth
    image: oitp-isov/api-auth
    secrets:
      - api-self
    environment:
      - PGAPPNAME=api-auth
      - PGHOST=sql
      - PGDATABASE=oitp
      - PGUSER=api-self
      - PGPASSWORD_FILE=/run/secrets/api-self
      - PGPOOL_SIZE=10
      - PGLOG_LEVEL=WARN
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  api-public:
    restart: unless-stopped
    build:
      context: ./backends
      args:
        - APP_PATH=api/public
    image: oitp-isov/api-public
    secrets:
      - api-public
    environment:
      - PGAPPNAME=api-public
      - PGHOST=sql
      - PGDATABASE=oitp
      - PGUSER=api-public
      - PGPASSWORD_FILE=/run/secrets/api-public
      - PGPOOL_SIZE=10
      - PGLOG_LEVEL=WARN
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  api-self:
    restart: unless-stopped
    build:
      context: ./backends
      args:
        - APP_PATH=api/self
    image: oitp-isov/api-self
    secrets:
      - api-self
    environment:
      - PGAPPNAME=api-self
      - PGHOST=sql
      - PGDATABASE=oitp
      - PGUSER=api-self
      - PGPASSWORD_FILE=/run/secrets/api-self
      - PGPOOL_SIZE=10
      - PGLOG_LEVEL=WARN
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  app:
    restart: unless-stopped
    build: ./frontends/app
    image: oitp-isov/frontend-app
    networks:
      default:

  portal:
    restart: unless-stopped
    build: ./frontends/portal
    image: oitp-isov/frontend-portal
    networks:
      default:

  nginx:
    restart: unless-stopped
    build: ./nginx
    image: oitp-isov/nginx
    depends_on:
      - api-auth
      - api-public
      - api-self
      - app
      - portal
    links:
      - api-auth
      - api-public
      - api-self
      - app
      - portal
    networks:
      default:

volumes:
  data-volume:

secrets:
  api-admin:
    file: ./secret-api-admin.env
  api-payment:
    file: ./secret-api-payment.env
  api-public:
    file: ./secret-api-public.env
  api-self:
    file: ./secret-api-self.env
  daemon-cron:
    file: ./secret-daemon-cron.env
  daemon-msg:
    file: ./secret-daemon-msg.env
  daemon-payment:
    file: ./secret-daemon-payment.env