version: "3.7"

services:

  sql:
    restart: unless-stopped
    build: ./sql
    image: oitp-isov/sql
    volumes:
      - data-volume:/var/lib/postgresql/data
    environment:
      - LANG=ru_RU.utf8
      - PGDATABASE=oitp
    networks:
      default:

  api-auth:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_PATH=auth
    image: oitp-isov/api-auth
    secrets:
      - secret-api-public
    env_file:
      - ./environment
    environment:
      - POSTGRES_APPNAME=api-auth
      - POSTGRES_USER=api-public
      - POSTGRES_PASSWORD_FILE=/run/secrets/secret-api-public
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  api-public-info:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_PATH=public/info
    image: oitp-isov/api-public-info
    secrets:
      - secret-api-public
    env_file:
      - ./environment
    environment:
      - POSTGRES_APPNAME=api-public-info
      - POSTGRES_USER=api-public
      - POSTGRES_PASSWORD_FILE=/run/secrets/secret-api-public
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  api-public-invite:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_PATH=public/invite
    image: oitp-isov/api-public-invite
    secrets:
      - secret-api-public
    env_file:
      - ./environment
    environment:
      - POSTGRES_APPNAME=api-public-invite
      - POSTGRES_USER=api-public
      - POSTGRES_PASSWORD_FILE=/run/secrets/secret-api-public
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  api-public-login:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_PATH=public/login
    image: oitp-isov/api-public-login
    secrets:
      - secret-api-public
    env_file:
      - ./environment
    environment:
      - POSTGRES_APPNAME=api-public-login
      - POSTGRES_USER=api-public
      - POSTGRES_PASSWORD_FILE=/run/secrets/secret-api-public
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  api-self-invite:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_PATH=self/invite
    image: oitp-isov/api-self-invite
    secrets:
      - secret-api-self
    env_file:
      - ./environment
    environment:
      - POSTGRES_APPNAME=api-self-invite
      - POSTGRES_USER=api-public
      - POSTGRES_PASSWORD_FILE=/run/secrets/secret-api-self
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  api-self-login:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_PATH=self/login
    image: oitp-isov/api-self-login
    secrets:
      - secret-api-self
    env_file:
      - ./environment
    environment:
      - POSTGRES_APPNAME=api-self-login
      - POSTGRES_USER=api-public
      - POSTGRES_PASSWORD_FILE=/run/secrets/secret-api-self
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  api-self-progress:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_PATH=self/progress
    image: oitp-isov/api-self-progress
    secrets:
      - secret-api-self
    env_file:
      - ./environment
    environment:
      - POSTGRES_APPNAME=api-self-progress
      - POSTGRES_USER=api-public
      - POSTGRES_PASSWORD_FILE=/run/secrets/secret-api-self
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  api-self-training:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_PATH=self/training
    image: oitp-isov/api-self-training
    secrets:
      - secret-api-self
    env_file:
      - ./environment
    environment:
      - POSTGRES_APPNAME=api-self-training
      - POSTGRES_USER=api-public
      - POSTGRES_PASSWORD_FILE=/run/secrets/secret-api-self
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  api-self-user:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_PATH=self/user
    image: oitp-isov/api-self-user
    secrets:
      - secret-api-self
    env_file:
      - ./environment
    environment:
      - POSTGRES_APPNAME=api-self-user
      - POSTGRES_USER=api-public
      - POSTGRES_PASSWORD_FILE=/run/secrets/secret-api-self
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  app:
    restart: unless-stopped
    build: ./frontends/app
    image: oitp-isov/frontend-app
    networks:
      default:

  portal:
    restart: unless-stopped
    build: ./frontends/portal
    image: oitp-isov/frontend-portal
    networks:
      default:

  nginx:
    restart: unless-stopped
    build: ./nginx
    image: oitp-isov/nginx
    depends_on:
      - api-auth
      - api-public-info
      - api-public-invite
      - api-public-login
      - api-self-invite
      - api-self-login
      - api-self-progress
      - api-self-user
      - app
      - portal
    links:
      - api-auth
      - api-public-info
      - api-public-invite
      - api-public-login
      - api-self-invite
      - api-self-login
      - api-self-progress
      - api-self-user
      - app
      - portal
    networks:
      default:

volumes:
  data-volume:

secrets:
  secret-api-public:
    file: ./secret-api-public.env
  secret-api-self:
    file: ./secret-api-self.env
  secret-smtp:
    file: ./secret-smtp.env
