version: "3.7"

services:

  sql:
    restart: unless-stopped
    build: ./sql
    image: oitp-isov/sql
    volumes:
      - data-volume:/var/lib/postgresql/data
    secrets:
      - secret-sql-root
    env_file:
      - ./environment
    environment:
      - LANG=ru_RU.utf8
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD_FILE=/run/secrets/secret-sql-root
    networks:
      default:

  api-auth:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_PATH=auth
    image: oitp-isov/api-auth
    secrets:
      - secret-api-public
    env_file:
      - ./environment
    environment:
      - POSTGRES_APPNAME=api-auth
      - POSTGRES_USER=api-public
      - POSTGRES_PASSWORD=API-P@Ssw0rd
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  api-public-info:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_PATH=public/info
    image: oitp-isov/api-public-info
    secrets:
      - secret-api-public
    env_file:
      - ./environment
    environment:
      - POSTGRES_APPNAME=api-public-info
      - POSTGRES_USER=api-public
      - POSTGRES_PASSWORD=API-P@Ssw0rd
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  api-public-progress:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_PATH=public/progress
    image: oitp-isov/api-public-progress
    secrets:
      - secret-api-public
    env_file:
      - ./environment
    environment:
      - POSTGRES_APPNAME=api-public-progress
      - POSTGRES_USER=api-public
      - POSTGRES_PASSWORD=API-P@Ssw0rd
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  api-public-user:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_PATH=public/user
    image: oitp-isov/api-public-user
    secrets:
      - secret-api-public
    env_file:
      - ./environment
    environment:
      - POSTGRES_APPNAME=api-public-user
      - POSTGRES_USER=api-public
      - POSTGRES_PASSWORD=API-P@Ssw0rd
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  api-public-training:
    restart: unless-stopped
    build:
      context: ./api
      args:
        - APP_PATH=public/training
    image: oitp-isov/api-public-training
    secrets:
      - secret-api-public
    env_file:
      - ./environment
    environment:
      - POSTGRES_APPNAME=api-public-training
      - POSTGRES_USER=api-public
      - POSTGRES_PASSWORD=API-P@Ssw0rd
    depends_on:
      - sql
    links:
      - sql
    networks:
      default:

  app:
    restart: unless-stopped
    build: ./frontends/app
    image: oitp-isov/frontend-app
    networks:
      default:

  nginx:
    restart: unless-stopped
    build: ./nginx
    image: oitp-isov/nginx
    depends_on:
      - api-auth
      - api-public-info
      - api-public-progress
      - api-public-user
      - api-public-training
      - app
    links:
      - api-auth
      - api-public-info
      - api-public-progress
      - api-public-user
      - api-public-training
      - app
    networks:
      default:

volumes:
  data-volume:

secrets:
  secret-sql-root:
    file: ./secret-sql-root.env
  secret-api-public:
    file: ./secret-api-public.env
