CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA pg_catalog;
CREATE EXTENSION IF NOT EXISTS "pgcrypto"  WITH SCHEMA pg_catalog;

CREATE SCHEMA IF NOT EXISTS admin;
CREATE SCHEMA IF NOT EXISTS private;
CREATE SCHEMA IF NOT EXISTS public;
CREATE SCHEMA IF NOT EXISTS self;

REVOKE CREATE ON SCHEMA admin FROM PUBLIC;
REVOKE CREATE ON SCHEMA private FROM PUBLIC;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE CREATE ON SCHEMA self FROM PUBLIC;

CREATE ROLE "api-admin" WITH NOINHERIT NOLOGIN PASSWORD NULL;
ALTER ROLE "api-admin" SET search_path = "$user";
GRANT USAGE ON SCHEMA "admin" TO "api-admin";

CREATE ROLE "api-public" WITH NOINHERIT NOLOGIN PASSWORD NULL;
ALTER ROLE "api-public" SET search_path = "$user";
GRANT USAGE ON SCHEMA "public" TO "api-public";

CREATE ROLE "api-self" WITH NOINHERIT NOLOGIN PASSWORD NULL;
ALTER ROLE "api-self" SET search_path = "$user";
GRANT USAGE ON SCHEMA "self" TO "api-self";
