CREATE SCHEMA IF NOT EXISTS admin;
REVOKE ALL PRIVILEGES ON SCHEMA admin FROM PUBLIC;

CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL PRIVILEGES ON SCHEMA private FROM PUBLIC;

CREATE SCHEMA IF NOT EXISTS public;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA "public" TO PUBLIC;

CREATE SCHEMA IF NOT EXISTS self;
REVOKE ALL PRIVILEGES ON SCHEMA self FROM PUBLIC;
