

export const SHAPES = [
  "/icons/shapes/circle.svg",
  // "/icons/shapes/cone-1.svg",
  // "/icons/shapes/cone-2.svg",
  // "/icons/shapes/cone-3.svg",
  // "/icons/shapes/cone-4.svg",
  // "/icons/shapes/cone-5.svg",
  // "/icons/shapes/cone-6.svg",
  // "/icons/shapes/cone-7.svg",
  // "/icons/shapes/cone-8.svg",
  "/icons/shapes/cone.svg",
  // "/icons/shapes/cube-1.svg",
  // "/icons/shapes/cube-2.svg",
  "/icons/shapes/cube.svg",
  // "/icons/shapes/cylinder-1.svg",
  // "/icons/shapes/cylinder-2.svg",
  // "/icons/shapes/cylinder-3.svg",
  // "/icons/shapes/cylinder-4.svg",
  // "/icons/shapes/cylinder-5.svg",
  // "/icons/shapes/cylinder-6.svg",
  // "/icons/shapes/cylinder-7.svg",
  // "/icons/shapes/cylinder-8.svg",
  "/icons/shapes/cylinder.svg",
  // "/icons/shapes/dodecahedron-1.svg",
  // "/icons/shapes/dodecahedron-2.svg",
  // "/icons/shapes/dodecahedron-3.svg",
  // "/icons/shapes/dodecahedron-4.svg",
  // "/icons/shapes/dodecahedron-5.svg",
  // "/icons/shapes/dodecahedron-6.svg",
  "/icons/shapes/dodecahedron.svg",
  "/icons/shapes/hexagon.svg",
  "/icons/shapes/hexahedron-1.svg",
  "/icons/shapes/hexahedron-2.svg",
  "/icons/shapes/hexahedron.svg",
  // "/icons/shapes/icosahedron-1.svg",
  // "/icons/shapes/icosahedron.svg",
  // "/icons/shapes/octahedron-1.svg",
  // "/icons/shapes/octahedron-2.svg",
  "/icons/shapes/octahedron.svg",
  "/icons/shapes/pentagon.svg",
  // "/icons/shapes/pyramid-1.svg",
  // "/icons/shapes/pyramid-2.svg",
  "/icons/shapes/pyramid.svg",
  "/icons/shapes/rectangle.svg",
  // "/icons/shapes/sphere-1.svg",
  // "/icons/shapes/sphere-2.svg",
  "/icons/shapes/sphere.svg",
  "/icons/shapes/square.svg",
  // "/icons/shapes/tetrahedron-1.svg",
  // "/icons/shapes/tetrahedron-2.svg",
  // "/icons/shapes/tetrahedron-3.svg",
  "/icons/shapes/tetrahedron.svg",
  // "/icons/shapes/triangle-1.svg",
  // "/icons/shapes/triangle-2.svg",
  // "/icons/shapes/triangle.svg",
]