CREATE SCHEMA IF NOT EXISTS msg;
REVOKE CREATE ON SCHEMA msg FROM PUBLIC;

CREATE ROLE "api-msg" WITH NOINHERIT NOLOGIN PASSWORD NULL;
ALTER ROLE "api-msg" SET search_path = "$user";
GRANT USAGE ON SCHEMA "msg" TO "api-msg";
