
export const ICONS = [
"Action 2.svg",
"Action.svg",
"Add Image.svg",
"Add Ticket.svg",
"Advertising.svg",
"Alien.svg",
"Animation.svg",
"Apple TV.svg",
"Asteroid.svg",
"Astronaut.svg",
"Audience.svg",
"Av Receiver.svg",
"Ballet Shoes.svg",
"Binoculars.svg",
"Bunch Flowers.svg",
"Cable Release.svg",
"Camcorder Pro.svg",
"Camcorder.svg",
"Camera Addon.svg",
"Camera Automation.svg",
"Camera Identification.svg",
"Camera.svg",
"Captain America.svg",
"Channel Mosaic.svg",
"Clapperboard.svg",
"Close Up Mode.svg",
"Comedy 2.svg",
"Comedy.svg",
"Comet.svg",
"Compact Camera.svg",
"Crime.svg",
"Dance With Devil.svg",
"Delete Ticket.svg",
"Detective.svg",
"Documentary.svg",
"Drama.svg",
"Edit Image.svg",
"Facepalm.svg",
"Family.svg",
"Fantasy.svg",
"Film Noir.svg",
"Film Reel.svg",
"Film.svg",
"Gallery.svg",
"Grey.svg",
"Historical.svg",
"Horror.svg",
"IMDb.svg",
"Idea.svg",
"Integrated Webcam.svg",
"Iron Man.svg",
"Landscape.svg",
"Living Room.svg",
"Martian.svg",
"Moon.svg",
"Multiple Cameras.svg",
"Music.svg",
"Musical.svg",
"News.svg",
"Night Landscape.svg",
"Night Portrait.svg",
"Ninja Turtle.svg",
"No Idea.svg",
"Novel.svg",
"Old Time Camera.svg",
"Opera Glasses.svg",
"Panorama.svg",
"Planet.svg",
"Podium With Audience.svg",
"Podium With Speaker.svg",
"Portrait Mode.svg",
"Predator.svg",
"Puzzle.svg",
"Rating.svg",
"Remove Image.svg",
"Rotate Camera.svg",
"SDTV.svg",
"SLR Back Side.svg",
"Sci Fi.svg",
"Scream.svg",
"Selfie.svg",
"Short.svg",
"Speaker.svg",
"Sport.svg",
"Sports Mode.svg",
"Stack of Photos.svg",
"Starred Ticket.svg",
"Start.svg",
"Steve Jobs.svg",
"Switch Camera.svg",
"TV.svg",
"Theatre Mask.svg",
"Thriller.svg",
"Ticket.svg",
"Undergo Insomnia.svg",
"Video File.svg",
"Video Projector.svg",
"Watch TV In Bed.svg",
"Western.svg",
"Widescreen TV.svg",
]