CREATE SCHEMA IF NOT EXISTS cron;
REVOKE CREATE ON SCHEMA cron FROM PUBLIC;

CREATE ROLE "api-cron" WITH NOINHERIT NOLOGIN PASSWORD NULL;
ALTER ROLE "api-cron" SET search_path = "$user";
GRANT USAGE ON SCHEMA "cron" TO "api-cron";
